/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

/**
 *
 * @author felip
 */
public class DadosEquipe extends javax.swing.JFrame {

    /**
     * Creates new form DadosEquipe
     */
    public DadosEquipe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlJogadoresNaEquipe = new javax.swing.JPanel();
        lblNomeJogador = new javax.swing.JLabel();
        lblSobrenomeJogador = new javax.swing.JLabel();
        lblNacionalidadeJogador = new javax.swing.JLabel();
        pnlPosicaoJogador = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        txtPesquisarNome = new javax.swing.JButton();
        txtPesquisarSobrenome = new javax.swing.JButton();
        txtPesquisarNacionalidade = new javax.swing.JButton();
        lblPesquisarPosicao = new javax.swing.JButton();
        btnAdicionarJogador = new javax.swing.JButton();
        btnRemoverJogador = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJogadoresEquipe = new javax.swing.JTable();
        btnCancelarEquipe = new javax.swing.JButton();
        btnSalvarEquipe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jogadores na Equipe");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/Images/jogador.png")).getImage());

        pnlJogadoresNaEquipe.setBackground(new java.awt.Color(0, 153, 102));
        pnlJogadoresNaEquipe.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jogadores na Equipe", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        lblNomeJogador.setText("Nome:");

        lblSobrenomeJogador.setText("Sobrenome:");

        lblNacionalidadeJogador.setText("Nacionalidade:");

        pnlPosicaoJogador.setText("Posição:");

        txtPesquisarNome.setText("Pesquisar");

        txtPesquisarSobrenome.setText("Pesquisar");

        txtPesquisarNacionalidade.setText("Pesquisar");

        lblPesquisarPosicao.setText("Pesquisar");

        javax.swing.GroupLayout pnlJogadoresNaEquipeLayout = new javax.swing.GroupLayout(pnlJogadoresNaEquipe);
        pnlJogadoresNaEquipe.setLayout(pnlJogadoresNaEquipeLayout);
        pnlJogadoresNaEquipeLayout.setHorizontalGroup(
            pnlJogadoresNaEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJogadoresNaEquipeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlJogadoresNaEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlJogadoresNaEquipeLayout.createSequentialGroup()
                        .addComponent(lblNomeJogador)
                        .addGap(56, 56, 56)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlJogadoresNaEquipeLayout.createSequentialGroup()
                        .addGroup(pnlJogadoresNaEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNacionalidadeJogador)
                            .addComponent(pnlPosicaoJogador))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlJogadoresNaEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4)))
                    .addGroup(pnlJogadoresNaEquipeLayout.createSequentialGroup()
                        .addComponent(lblSobrenomeJogador)
                        .addGap(28, 28, 28)
                        .addComponent(jTextField2)))
                .addGap(18, 18, 18)
                .addGroup(pnlJogadoresNaEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPesquisarNome)
                    .addComponent(txtPesquisarSobrenome)
                    .addComponent(txtPesquisarNacionalidade)
                    .addComponent(lblPesquisarPosicao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlJogadoresNaEquipeLayout.setVerticalGroup(
            pnlJogadoresNaEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJogadoresNaEquipeLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlJogadoresNaEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeJogador)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisarNome))
                .addGap(18, 18, 18)
                .addGroup(pnlJogadoresNaEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSobrenomeJogador)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisarSobrenome))
                .addGap(18, 18, 18)
                .addGroup(pnlJogadoresNaEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNacionalidadeJogador)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisarNacionalidade))
                .addGap(18, 18, 18)
                .addGroup(pnlJogadoresNaEquipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pnlPosicaoJogador)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPesquisarPosicao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAdicionarJogador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/adicionarCliente.png"))); // NOI18N
        btnAdicionarJogador.setText("Adicionar Jogador");

        btnRemoverJogador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/excluirCliente.png"))); // NOI18N
        btnRemoverJogador.setText("Remover Jogador");

        tblJogadoresEquipe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Sobrenome", "Nacionalidade", "Posicao"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblJogadoresEquipe);

        btnCancelarEquipe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cancelar.png"))); // NOI18N
        btnCancelarEquipe.setText("Cancelar");

        btnSalvarEquipe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/salvar1.png"))); // NOI18N
        btnSalvarEquipe.setText("Salvar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdicionarJogador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemoverJogador)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlJogadoresNaEquipe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvarEquipe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelarEquipe)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlJogadoresNaEquipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarJogador)
                    .addComponent(btnRemoverJogador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarEquipe)
                    .addComponent(btnSalvarEquipe))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DadosEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DadosEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DadosEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DadosEquipe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DadosEquipe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarJogador;
    private javax.swing.JButton btnCancelarEquipe;
    private javax.swing.JButton btnRemoverJogador;
    private javax.swing.JButton btnSalvarEquipe;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel lblNacionalidadeJogador;
    private javax.swing.JLabel lblNomeJogador;
    private javax.swing.JButton lblPesquisarPosicao;
    private javax.swing.JLabel lblSobrenomeJogador;
    private javax.swing.JPanel pnlJogadoresNaEquipe;
    private javax.swing.JLabel pnlPosicaoJogador;
    private javax.swing.JTable tblJogadoresEquipe;
    private javax.swing.JButton txtPesquisarNacionalidade;
    private javax.swing.JButton txtPesquisarNome;
    private javax.swing.JButton txtPesquisarSobrenome;
    // End of variables declaration//GEN-END:variables
}
