/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

/**
 *
 * @author felip
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloPrincipal = new javax.swing.JLabel();
        btnJogadoresPrincipal = new javax.swing.JButton();
        btnTécnicosPrincipal = new javax.swing.JButton();
        btnArbitrosPrincipal = new javax.swing.JButton();
        btnEquipesPrincipal = new javax.swing.JButton();
        btnCampeonatosPrincipal = new javax.swing.JButton();
        btnPartidasPrincipal = new javax.swing.JButton();
        btnFecharPrincipal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Escolinha de Futebol");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/ball.png")).getImage());

        lblTituloPrincipal.setFont(new java.awt.Font("Rockwell Extra Bold", 1, 36)); // NOI18N
        lblTituloPrincipal.setText("Escolinha de Futebol Tok de Bola");
        lblTituloPrincipal.setToolTipText("");

        btnJogadoresPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/player.png"))); // NOI18N
        btnJogadoresPrincipal.setText("Jogadores");
        btnJogadoresPrincipal.setToolTipText("Dados de todos os jogadores da escolinha");
        btnJogadoresPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJogadoresPrincipalActionPerformed(evt);
            }
        });

        btnTécnicosPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/manager.png"))); // NOI18N
        btnTécnicosPrincipal.setText("Técnicos");
        btnTécnicosPrincipal.setToolTipText("Dados de todos os técnicos da escolinha");

        btnArbitrosPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/referee.png"))); // NOI18N
        btnArbitrosPrincipal.setText("Árbitros");
        btnArbitrosPrincipal.setToolTipText("Dados de todos os árbitros da escolinha");

        btnEquipesPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/team.png"))); // NOI18N
        btnEquipesPrincipal.setText("Equipes");
        btnEquipesPrincipal.setToolTipText("Dados de todas as equipes da escolinha");

        btnCampeonatosPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/league.png"))); // NOI18N
        btnCampeonatosPrincipal.setText("Campeonatos");
        btnCampeonatosPrincipal.setToolTipText("Dados de todos os campeonatos da escolinha");

        btnPartidasPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/match.png"))); // NOI18N
        btnPartidasPrincipal.setText("Partidas");
        btnPartidasPrincipal.setToolTipText("Dados de todas as partidas da escolinha");

        btnFecharPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        btnFecharPrincipal.setText("Fechar");
        btnFecharPrincipal.setToolTipText("Sair do programa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTituloPrincipal)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnJogadoresPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(btnEquipesPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTécnicosPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCampeonatosPrincipal))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPartidasPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(btnArbitrosPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(btnFecharPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(lblTituloPrincipal)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTécnicosPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnJogadoresPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnArbitrosPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnEquipesPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCampeonatosPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnPartidasPrincipal))
                .addGap(27, 27, 27)
                .addComponent(btnFecharPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnJogadoresPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJogadoresPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnJogadoresPrincipalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArbitrosPrincipal;
    private javax.swing.JButton btnCampeonatosPrincipal;
    private javax.swing.JButton btnEquipesPrincipal;
    private javax.swing.JButton btnFecharPrincipal;
    private javax.swing.JButton btnJogadoresPrincipal;
    private javax.swing.JButton btnPartidasPrincipal;
    private javax.swing.JButton btnTécnicosPrincipal;
    private javax.swing.JLabel lblTituloPrincipal;
    // End of variables declaration//GEN-END:variables
}
