/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Classes.Pessoa;
import Classes.Tecnico;
import java.awt.Cursor;
import java.time.LocalDate;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.io.*;

/**
 *
 * @author felip
 */
public class Tecnicos extends javax.swing.JFrame {
    static ArrayList<Tecnico> listaTecnicos = new ArrayList<>();
    private String botão;
    
    /**
     * Creates new form Tecnicos
     */
    public Tecnicos() {
        initComponents();
        
        File arquivo = new File("src/Dados/dadosTecnicos.txt");
        
        try {
            FileReader fr = new FileReader(arquivo);
            BufferedReader br = new BufferedReader(fr);
            
            while(br.ready()) {
                String[] linha = br.readLine().split(";");
                Tecnico tecnico = new Tecnico(linha[0], linha[1], linha[2], linha[3], Integer.parseInt(linha[4]), linha[5]);
                listaTecnicos.add(tecnico);
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível abrir o arquivo.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }       
        
        carregarTabelaTecnicos();
        
        setLocationRelativeTo(null);
        
        //Habilitar ou desabilitar funções
        btnNovoTecnico.setEnabled(true);
        btnSalvarTecnico.setEnabled(false);
        btnCancelarTecnico.setEnabled(false);
        btnEditarTecnico.setEnabled(false);
        btnExcluirTecnico.setEnabled(false);
        btnPesquisarTecnico.setEnabled(true);
        btnOKTecnico.setEnabled(false);
        
        //Habilitar ou desabilitar campos de textos
        txtNomeTecnicos.setEnabled(false);
        txtSobrenomeTecnicos.setEnabled(false);
        txtCPFTecnicos.setEnabled(false);
        txtSexoTecnicos.setEnabled(false);
        spnDiaTecnicos.setEnabled(false);
        spnMesTecnicos.setEnabled(false);
        spnAnoTecnicos.setEnabled(false);
    }

    //Carregar a tabela com tecnicos da lista
    public void carregarTabelaTecnicos(){
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Nome", "Sobrenome", "CPF", "Idade", "Sexo","Data Nascimento"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        for(int i=0;i<listaTecnicos.size();i++){
            Object linha[] = new Object[] {listaTecnicos.get(i).getNome(),
                                           listaTecnicos.get(i).getSobrenome(),
                                           listaTecnicos.get(i).getCpf(),
                                           listaTecnicos.get(i).getIdade(),
                                           listaTecnicos.get(i).getSexo(),
                                           listaTecnicos.get(i).getDataNascimento()};
            modelo.addRow(linha);
        }
        
        //Tabela recebe modelo
        tblTecnicos.setModel(modelo);
        
        tblTecnicos.getColumnModel().getColumn(0).setPreferredWidth(5);
        tblTecnicos.getColumnModel().getColumn(1).setPreferredWidth(20);
        tblTecnicos.getColumnModel().getColumn(2).setPreferredWidth(100);
        tblTecnicos.getColumnModel().getColumn(3).setPreferredWidth(50);
        tblTecnicos.getColumnModel().getColumn(4).setPreferredWidth(50);
        tblTecnicos.getColumnModel().getColumn(5).setPreferredWidth(50);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTecnicos = new javax.swing.JPanel();
        lblNomeTecnico = new javax.swing.JLabel();
        txtNomeTecnicos = new javax.swing.JTextField();
        lblSobrenomeTecnicos = new javax.swing.JLabel();
        txtSobrenomeTecnicos = new javax.swing.JTextField();
        lblCPFTecnicos = new javax.swing.JLabel();
        txtCPFTecnicos = new javax.swing.JTextField();
        lblIdadeTecnicos = new javax.swing.JLabel();
        lblSexoTecnicos = new javax.swing.JLabel();
        txtSexoTecnicos = new javax.swing.JTextField();
        btnOKTecnico = new javax.swing.JButton();
        spnMesTecnicos = new javax.swing.JSpinner();
        spnAnoTecnicos = new javax.swing.JSpinner();
        spnDiaTecnicos = new javax.swing.JSpinner();
        btnNovoTecnico = new javax.swing.JButton();
        btnSalvarTecnico = new javax.swing.JButton();
        btnCancelarTecnico = new javax.swing.JButton();
        btnEditarTecnico = new javax.swing.JButton();
        btnExcluirTecnico = new javax.swing.JButton();
        btnPesquisarTecnico = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTecnicos = new javax.swing.JTable();
        btnSairTecnico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Técnicos");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/manager.png")).getImage());

        pnlTecnicos.setBackground(new java.awt.Color(0, 153, 102));
        pnlTecnicos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados dos Técnicos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N
        pnlTecnicos.setToolTipText("Dados dos Técnicos");

        lblNomeTecnico.setText("Nome:");

        lblSobrenomeTecnicos.setText("Sobrenome:");

        lblCPFTecnicos.setText("CPF:");

        lblIdadeTecnicos.setText("Data de Nascimento:");

        lblSexoTecnicos.setText("Sexo:");

        btnOKTecnico.setText("OK");
        btnOKTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKTecnicoActionPerformed(evt);
            }
        });

        spnMesTecnicos.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));

        spnAnoTecnicos.setModel(new javax.swing.SpinnerNumberModel(2023, null, 2023, 1));

        spnDiaTecnicos.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        javax.swing.GroupLayout pnlTecnicosLayout = new javax.swing.GroupLayout(pnlTecnicos);
        pnlTecnicos.setLayout(pnlTecnicosLayout);
        pnlTecnicosLayout.setHorizontalGroup(
            pnlTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTecnicosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTecnicosLayout.createSequentialGroup()
                        .addComponent(lblIdadeTecnicos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnDiaTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(spnMesTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(spnAnoTecnicos))
                    .addGroup(pnlTecnicosLayout.createSequentialGroup()
                        .addGroup(pnlTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSobrenomeTecnicos)
                            .addComponent(lblCPFTecnicos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlTecnicosLayout.createSequentialGroup()
                                .addComponent(txtCPFTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnOKTecnico))
                            .addComponent(txtSobrenomeTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlTecnicosLayout.createSequentialGroup()
                        .addComponent(lblSexoTecnicos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSexoTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTecnicosLayout.createSequentialGroup()
                        .addComponent(lblNomeTecnico)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNomeTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(340, 340, 340))
        );
        pnlTecnicosLayout.setVerticalGroup(
            pnlTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTecnicosLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeTecnico)
                    .addComponent(txtNomeTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSobrenomeTecnicos)
                    .addComponent(txtSobrenomeTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPFTecnicos)
                    .addComponent(txtCPFTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOKTecnico))
                .addGap(18, 18, 18)
                .addGroup(pnlTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdadeTecnicos)
                    .addComponent(spnMesTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnAnoTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnDiaTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlTecnicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSexoTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSexoTecnicos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnNovoTecnico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/adicionar.png"))); // NOI18N
        btnNovoTecnico.setText("Novo");
        btnNovoTecnico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNovoTecnicoMouseEntered(evt);
            }
        });
        btnNovoTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoTecnicoActionPerformed(evt);
            }
        });

        btnSalvarTecnico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Salvar.png"))); // NOI18N
        btnSalvarTecnico.setText("Salvar");
        btnSalvarTecnico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalvarTecnicoMouseEntered(evt);
            }
        });
        btnSalvarTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarTecnicoActionPerformed(evt);
            }
        });

        btnCancelarTecnico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Cancelar.png"))); // NOI18N
        btnCancelarTecnico.setText("Cancelar");
        btnCancelarTecnico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarTecnicoMouseEntered(evt);
            }
        });
        btnCancelarTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarTecnicoActionPerformed(evt);
            }
        });

        btnEditarTecnico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/editarCliente.png"))); // NOI18N
        btnEditarTecnico.setText("Editar");
        btnEditarTecnico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditarTecnicoMouseEntered(evt);
            }
        });
        btnEditarTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarTecnicoActionPerformed(evt);
            }
        });

        btnExcluirTecnico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/excluirCliente.png"))); // NOI18N
        btnExcluirTecnico.setText("Excluir");
        btnExcluirTecnico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExcluirTecnicoMouseEntered(evt);
            }
        });
        btnExcluirTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirTecnicoActionPerformed(evt);
            }
        });

        btnPesquisarTecnico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Pesquisar.png"))); // NOI18N
        btnPesquisarTecnico.setText("Pesquisar");
        btnPesquisarTecnico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPesquisarTecnicoMouseEntered(evt);
            }
        });
        btnPesquisarTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarTecnicoActionPerformed(evt);
            }
        });

        tblTecnicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Sobrenome", "CPF", "Idade", "Sexo", "Data de Nascimento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTecnicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTecnicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTecnicos);

        btnSairTecnico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sair.png"))); // NOI18N
        btnSairTecnico.setText("Sair");
        btnSairTecnico.setToolTipText("Sair da tela de Técnicos");
        btnSairTecnico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSairTecnicoMouseEntered(evt);
            }
        });
        btnSairTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairTecnicoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnNovoTecnico)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvarTecnico)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelarTecnico)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditarTecnico)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluirTecnico)
                        .addGap(18, 18, 18)
                        .addComponent(btnPesquisarTecnico))
                    .addComponent(pnlTecnicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSairTecnico)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTecnicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoTecnico)
                    .addComponent(btnSalvarTecnico)
                    .addComponent(btnCancelarTecnico)
                    .addComponent(btnEditarTecnico)
                    .addComponent(btnExcluirTecnico)
                    .addComponent(btnPesquisarTecnico))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSairTecnico)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarTecnicoActionPerformed
        if(txtNomeTecnicos.getText().equals("") || txtSobrenomeTecnicos.getText().equals("") || txtCPFTecnicos.getText().equals("") || txtSexoTecnicos.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Todos os campos devem ser inseridos", "Mensagem", JOptionPane.PLAIN_MESSAGE);
        }
        else{
             String nome = txtNomeTecnicos.getText();
             String sobrenome = txtSobrenomeTecnicos.getText();
             String cpf = txtCPFTecnicos.getText();
             String sexo = txtSexoTecnicos.getText();
             String diaTecnico = String.valueOf(spnDiaTecnicos.getValue());
             String mesTecnico = String.valueOf(spnMesTecnicos.getValue());
             String anoTecnico = String.valueOf(spnAnoTecnicos.getValue());
             
             if(Integer.parseInt(diaTecnico)<10){
                 diaTecnico="0"+diaTecnico;
             }
             if(Integer.parseInt(mesTecnico)<10){
                 mesTecnico="0"+mesTecnico;
             }
             String dataNascimento = diaTecnico+"/"+mesTecnico+"/"+anoTecnico;
             
             DateTimeFormatter date =  DateTimeFormatter.ofPattern("dd/MM/yyyy");
             LocalDate dataNascimentoTecnico = LocalDate.parse(dataNascimento,date);
             LocalDate dataAtual = LocalDate.now();
             Period periodo = Period.between(dataNascimentoTecnico,dataAtual);
             int idade = periodo.getYears();
             

             if(botão.equals("novo")){
                 Tecnico tecnico = new Tecnico(nome,sobrenome,cpf,sexo,idade,dataNascimento);
                 listaTecnicos.add(tecnico);
                 File arquivo = new File("src/Dados/dadosTecnicos.txt");
                 try {
                     FileWriter fw = new FileWriter(arquivo, true);
                     BufferedWriter bw = new BufferedWriter(fw);
                     bw.write(nome + ";" + sobrenome + ";" + cpf + ";" + sexo + ";" + idade + ";" + dataNascimento);
                     bw.newLine();
                     bw.close();
                 } catch (IOException ex) {
                     JOptionPane.showMessageDialog(null, "Não foi possível abrir o arquivo.", "Erro", JOptionPane.ERROR_MESSAGE);
                     return;
                 }
                 JOptionPane.showMessageDialog(null, "Técnico cadastrado com sucesso", "Mensagem", JOptionPane.INFORMATION_MESSAGE);
             }
             else if(botão.equals("editar")){
                int index = tblTecnicos.getSelectedRow();
                File arquivo = new File("src/Dados/dadosTecnicos.txt");
                try { 
                ArrayList<String> temp = new ArrayList<>();
                FileReader fr = new FileReader(arquivo);
                BufferedReader br = new BufferedReader(fr);
                for(int j = 0; br.ready(); j++) {
                    if(j != index) {
                        String linha = br.readLine();
                        temp.add(linha);
                    } else {
                        br.readLine();
                        temp.add(nome + ";" + sobrenome + ";" + cpf + ";" + sexo + ";" + idade + ";" + dataNascimento);
                    }
                }
                br.close();
                FileWriter fw = new FileWriter(arquivo);
                BufferedWriter bw = new BufferedWriter(fw);
                for(String linha : temp) {
                    bw.write(linha);
                    bw.newLine();
                }
                bw.close();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(null, "Não foi posssível abrir o arquivo.", "Erro", 0);
                return;
            }
                 listaTecnicos.get(index).setNome(nome);
                 listaTecnicos.get(index).setSobrenome(sobrenome);
                 listaTecnicos.get(index).setCpf(cpf);
                 listaTecnicos.get(index).setSexo(sexo);
                 listaTecnicos.get(index).setIdade(idade);
                 listaTecnicos.get(index).setDataNascimento(dataNascimento);
             }

             //Carregar os dados do gerente na tabela
             carregarTabelaTecnicos();
             
             //Limpar os campos
             txtNomeTecnicos.setText("");
             txtSobrenomeTecnicos.setText("");
             txtCPFTecnicos.setText("");
             txtSexoTecnicos.setText("");
             spnDiaTecnicos.setValue(1);
             spnMesTecnicos.setValue(1);
             spnAnoTecnicos.setValue(2023);


             //Habilitar ou desabiltiar botões
             btnNovoTecnico.setEnabled(true);
             btnSalvarTecnico.setEnabled(false);
             btnCancelarTecnico.setEnabled(false);
             btnEditarTecnico.setEnabled(false);
             btnExcluirTecnico.setEnabled(false);
             btnPesquisarTecnico.setEnabled(true);
             btnOKTecnico.setEnabled(false);

             //Habilitar ou desabilitar campos de texto
             txtNomeTecnicos.setEnabled(false);
             txtSobrenomeTecnicos.setEnabled(false);
             txtCPFTecnicos.setEnabled(false);
             txtSexoTecnicos.setEnabled(false);
             spnDiaTecnicos.setEnabled(false);
             spnMesTecnicos.setEnabled(false);
             spnAnoTecnicos.setEnabled(false);
        }
    }//GEN-LAST:event_btnSalvarTecnicoActionPerformed
    private void btnSairTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairTecnicoActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnSairTecnicoActionPerformed
       
    private void btnNovoTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoTecnicoActionPerformed
        botão = "novo";
        //Limpar os campos
        txtNomeTecnicos.setText("");
        txtSobrenomeTecnicos.setText("");
        txtCPFTecnicos.setText("");
        txtSexoTecnicos.setText("");
        spnDiaTecnicos.setValue(1);
        spnMesTecnicos.setValue(1);
        spnAnoTecnicos.setValue(2023);

        //Habilitar ou desabilitar botões
        btnNovoTecnico.setEnabled(false);
        btnSalvarTecnico.setEnabled(true);
        btnCancelarTecnico.setEnabled(true);
        btnEditarTecnico.setEnabled(false);
        btnExcluirTecnico.setEnabled(false);
        btnPesquisarTecnico.setEnabled(false);
        btnOKTecnico.setEnabled(false);
        
        //Habilitar ou desabilitar campos de texto
        txtNomeTecnicos.setEnabled(true);
        txtSobrenomeTecnicos.setEnabled(true);
        txtCPFTecnicos.setEnabled(true);
        txtSexoTecnicos.setEnabled(true);
        spnDiaTecnicos.setEnabled(true);
        spnMesTecnicos.setEnabled(true);
        spnAnoTecnicos.setEnabled(true);
        
        //Deixar cursor no txtcódigo
        txtNomeTecnicos.requestFocus();
    }//GEN-LAST:event_btnNovoTecnicoActionPerformed

    private void btnCancelarTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarTecnicoActionPerformed
        //Limpar os campos
        txtNomeTecnicos.setText("");
        txtSobrenomeTecnicos.setText("");
        txtCPFTecnicos.setText("");
        txtSexoTecnicos.setText("");
        spnDiaTecnicos.setValue(1);
        spnMesTecnicos.setValue(1);
        spnAnoTecnicos.setValue(2023);
        

        //Habilitar ou desabiltiar botões
        btnNovoTecnico.setEnabled(true);
        btnSalvarTecnico.setEnabled(false);
        btnCancelarTecnico.setEnabled(false);
        btnEditarTecnico.setEnabled(false);
        btnExcluirTecnico.setEnabled(false);
        btnPesquisarTecnico.setEnabled(true);
        btnOKTecnico.setEnabled(false);
        
        //Habilitar ou desabilitar campos de texto
        txtNomeTecnicos.setEnabled(false);
        txtSobrenomeTecnicos.setEnabled(false);
        txtCPFTecnicos.setEnabled(false);
        txtSexoTecnicos.setEnabled(false);
        spnDiaTecnicos.setEnabled(false);
        spnMesTecnicos.setEnabled(false);
        spnAnoTecnicos.setEnabled(false);
    }//GEN-LAST:event_btnCancelarTecnicoActionPerformed

    private void tblTecnicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTecnicosMouseClicked
        int i = tblTecnicos.getSelectedRow();
        
        if(i>=0 && i<listaTecnicos.size()){
            Tecnico tecnico = listaTecnicos.get(i);
            String data = tecnico.getDataNascimento();
            String dia = data.split("/")[0];
            String mes = data.split("/")[1];
            String ano = data.split("/")[2];
            txtNomeTecnicos.setText(String.valueOf(tecnico.getNome()));
            txtSobrenomeTecnicos.setText(String.valueOf(tecnico.getSobrenome()));
            txtCPFTecnicos.setText(String.valueOf(tecnico.getCpf()));
            txtSexoTecnicos.setText(String.valueOf(tecnico.getSexo()));
            spnDiaTecnicos.setValue(Integer.parseInt(dia));
            spnMesTecnicos.setValue(Integer.parseInt(mes));
            spnAnoTecnicos.setValue(Integer.parseInt(ano));
        }
        
        //Habilitar ou desabiltiar botões
        btnNovoTecnico.setEnabled(true);
        btnSalvarTecnico.setEnabled(false);
        btnCancelarTecnico.setEnabled(false);
        btnEditarTecnico.setEnabled(true);
        btnExcluirTecnico.setEnabled(true);
        btnPesquisarTecnico.setEnabled(true);
        btnOKTecnico.setEnabled(false);
        
        //Habilitar ou desabilitar campos de texto
        txtNomeTecnicos.setEnabled(false);
        txtSobrenomeTecnicos.setEnabled(false);
        txtCPFTecnicos.setEnabled(false);
        txtSexoTecnicos.setEnabled(false);
        spnDiaTecnicos.setEnabled(false);
        spnMesTecnicos.setEnabled(false);
        spnAnoTecnicos.setEnabled(false);
    }//GEN-LAST:event_tblTecnicosMouseClicked

    private void btnEditarTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarTecnicoActionPerformed
        botão = "editar";
        
        //Habilitar ou desabiltiar botões
        btnNovoTecnico.setEnabled(false);
        btnSalvarTecnico.setEnabled(true);
        btnCancelarTecnico.setEnabled(true);
        btnEditarTecnico.setEnabled(false);
        btnExcluirTecnico.setEnabled(false);
        btnPesquisarTecnico.setEnabled(false);
        btnOKTecnico.setEnabled(false);
        
        //Habilitar ou desabilitar campos de texto
        txtNomeTecnicos.setEnabled(true);
        txtSobrenomeTecnicos.setEnabled(true);
        txtCPFTecnicos.setEnabled(true);
        txtSexoTecnicos.setEnabled(true);
        spnDiaTecnicos.setEnabled(true);
        spnMesTecnicos.setEnabled(true);
        spnAnoTecnicos.setEnabled(true);
        
        txtNomeTecnicos.requestFocus();
    }//GEN-LAST:event_btnEditarTecnicoActionPerformed

    private void btnExcluirTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirTecnicoActionPerformed
        int j = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir esse tecnico?", "Atenção!", JOptionPane.WARNING_MESSAGE);
        
        if(j==0){
            int index = tblTecnicos.getSelectedRow();

            String tecnico = listaTecnicos.get(index).getNome() + ";" + listaTecnicos.get(index).getSobrenome() + ";" + listaTecnicos.get(index).getCpf() + ";" + listaTecnicos.get(index).getSexo() + ";" + listaTecnicos.get(index).getIdade() + ";" + listaTecnicos.get(index).getDataNascimento();

            File arquivo = new File("src/Dados/dadosTecnicos.txt");

            try{
                FileReader fr = new FileReader(arquivo);
                BufferedReader br = new BufferedReader(fr);

                String linha = br.readLine();
                ArrayList<String> salvar = new ArrayList();

                while(linha!= null){
                    if(linha.equals(tecnico) == false  ){
                        salvar.add(linha);
                    }
                    linha = br.readLine();
                }


                br.close();
                fr.close();
                FileWriter fw2 = new FileWriter(arquivo,true);
                fw2.close();

                FileWriter fw = new FileWriter(arquivo);
                BufferedWriter bw = new BufferedWriter(fw);

                for(int i=0;i<salvar.size();i++){
                    bw.write(salvar.get(i));
                    bw.newLine();
                }
                fw.close();
                bw.close();

            }catch(IOException  ex){
                JOptionPane.showMessageDialog(null, "Não foi posssível abrir o arquivo.", "Erro", 0);
                return;
            }

            if(index>=0 && index<listaTecnicos.size()){
                listaTecnicos.remove(index);
            }

            carregarTabelaTecnicos();

            //Limpar os campos
            txtNomeTecnicos.setText("");
            txtSobrenomeTecnicos.setText("");
            txtCPFTecnicos.setText("");
            txtSexoTecnicos.setText("");
            spnDiaTecnicos.setValue(1);
            spnMesTecnicos.setValue(1);
            spnAnoTecnicos.setValue(2023);


            //Habilitar ou desabiltiar botões
            btnNovoTecnico.setEnabled(true);
            btnSalvarTecnico.setEnabled(false);
            btnCancelarTecnico.setEnabled(false);
            btnEditarTecnico.setEnabled(false);
            btnExcluirTecnico.setEnabled(false);
            btnPesquisarTecnico.setEnabled(true);
            btnOKTecnico.setEnabled(false);

            //Habilitar ou desabilitar campos de texto
            txtNomeTecnicos.setEnabled(false);
            txtSobrenomeTecnicos.setEnabled(false);
            txtCPFTecnicos.setEnabled(false);
            txtSexoTecnicos.setEnabled(false);
            spnDiaTecnicos.setEnabled(false);
            spnMesTecnicos.setEnabled(false);
            spnAnoTecnicos.setEnabled(false);
        }
    }//GEN-LAST:event_btnExcluirTecnicoActionPerformed

    private void btnPesquisarTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarTecnicoActionPerformed
        if(listaTecnicos.isEmpty()){
            JOptionPane.showMessageDialog(null,"Nenhum tecnico está cadastrado", "Mensagem", JOptionPane.PLAIN_MESSAGE);
        }
        else{
            //Limpar os campos
            txtNomeTecnicos.setText("");
            txtSobrenomeTecnicos.setText("");
            txtCPFTecnicos.setText("");
            txtSexoTecnicos.setText("");
            spnDiaTecnicos.setValue(1);
            spnMesTecnicos.setValue(1);
            spnAnoTecnicos.setValue(2023);


           //Habilitar ou desabiltiar botões
           btnNovoTecnico.setEnabled(false);
           btnSalvarTecnico.setEnabled(false);
           btnCancelarTecnico.setEnabled(true);
           btnEditarTecnico.setEnabled(false);
           btnExcluirTecnico.setEnabled(false);
           btnPesquisarTecnico.setEnabled(false);
           btnOKTecnico.setEnabled(true);

           //Habilitar ou desabilitar campos de texto
            txtNomeTecnicos.setEnabled(false);
            txtSobrenomeTecnicos.setEnabled(false);
            txtCPFTecnicos.setEnabled(true);
            txtSexoTecnicos.setEnabled(false);
            spnDiaTecnicos.setEnabled(false);
            spnMesTecnicos.setEnabled(false);
            spnAnoTecnicos.setEnabled(false);

           txtCPFTecnicos.requestFocus();   
        }
    }//GEN-LAST:event_btnPesquisarTecnicoActionPerformed

    private void btnOKTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKTecnicoActionPerformed
        if(txtCPFTecnicos.getText().equals("")){
            JOptionPane.showMessageDialog(null, "O cpf deve ser informado", "Mensagem", JOptionPane.PLAIN_MESSAGE);
        }
        else{
            Tecnico tecnico;
            String nome = "",sobrenome = "",cpf = "",sexo = "",dia="",mes="",ano="";
            String cpfTecnico = txtCPFTecnicos.getText();
            for(int i=0;i<listaTecnicos.size();i++){
                tecnico = listaTecnicos.get(i);
                if(cpfTecnico.equals(tecnico.getCpf())){
                    String data = tecnico.getDataNascimento();
                    dia = data.split("/")[0];
                    mes = data.split("/")[1];
                    ano = data.split("/")[2];
                    nome = tecnico.getNome();
                    sobrenome = tecnico.getSobrenome();
                    sexo = tecnico.getSexo();
                    cpf = tecnico.getCpf();
                }
            }
            
            if(cpf.equals("")){
                JOptionPane.showMessageDialog(null, "Este tecnico não existe", "Mensagem", JOptionPane.PLAIN_MESSAGE);
                //Limpar os campos
                txtNomeTecnicos.setText("");
                txtSobrenomeTecnicos.setText("");
                txtCPFTecnicos.setText("");
                txtSexoTecnicos.setText("");
                spnDiaTecnicos.setValue(1);
                spnMesTecnicos.setValue(1);
                spnAnoTecnicos.setValue(2023);
            }
            else{
                txtNomeTecnicos.setText(nome);
                txtSobrenomeTecnicos.setText(sobrenome);
                txtSexoTecnicos.setText(sexo);
                txtCPFTecnicos.setText(cpf);
                spnDiaTecnicos.setValue(Integer.parseInt(dia));
                spnMesTecnicos.setValue(Integer.parseInt(mes));
                spnAnoTecnicos.setValue(Integer.parseInt(ano));
            }
            
            txtCPFTecnicos.selectAll();
            txtCPFTecnicos.requestFocus();
        }
    }//GEN-LAST:event_btnOKTecnicoActionPerformed

    private void btnNovoTecnicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoTecnicoMouseEntered
        btnNovoTecnico.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnNovoTecnicoMouseEntered

    private void btnSalvarTecnicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarTecnicoMouseEntered
        btnSalvarTecnico.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnSalvarTecnicoMouseEntered

    private void btnCancelarTecnicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarTecnicoMouseEntered
        btnCancelarTecnico.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnCancelarTecnicoMouseEntered

    private void btnEditarTecnicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditarTecnicoMouseEntered
        btnEditarTecnico.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnEditarTecnicoMouseEntered

    private void btnExcluirTecnicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExcluirTecnicoMouseEntered
        btnExcluirTecnico.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnExcluirTecnicoMouseEntered

    private void btnPesquisarTecnicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarTecnicoMouseEntered
        btnPesquisarTecnico.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnPesquisarTecnicoMouseEntered

    private void btnSairTecnicoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSairTecnicoMouseEntered
        btnSairTecnico.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_btnSairTecnicoMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tecnicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tecnicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tecnicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tecnicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tecnicos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarTecnico;
    private javax.swing.JButton btnEditarTecnico;
    private javax.swing.JButton btnExcluirTecnico;
    private javax.swing.JButton btnNovoTecnico;
    private javax.swing.JButton btnOKTecnico;
    private javax.swing.JButton btnPesquisarTecnico;
    private javax.swing.JButton btnSairTecnico;
    private javax.swing.JButton btnSalvarTecnico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCPFTecnicos;
    private javax.swing.JLabel lblIdadeTecnicos;
    private javax.swing.JLabel lblNomeTecnico;
    private javax.swing.JLabel lblSexoTecnicos;
    private javax.swing.JLabel lblSobrenomeTecnicos;
    private javax.swing.JPanel pnlTecnicos;
    private javax.swing.JSpinner spnAnoTecnicos;
    private javax.swing.JSpinner spnDiaTecnicos;
    private javax.swing.JSpinner spnMesTecnicos;
    private javax.swing.JTable tblTecnicos;
    private javax.swing.JTextField txtCPFTecnicos;
    private javax.swing.JTextField txtNomeTecnicos;
    private javax.swing.JTextField txtSexoTecnicos;
    private javax.swing.JTextField txtSobrenomeTecnicos;
    // End of variables declaration//GEN-END:variables
}
